Repository digitalungdom-se/digitalungdom.se, pull requests merged in 2020-12, with the labels that each got.

#89 Image optimization
  .gitignore
  .gitlab-ci.yml
  .vscode/settings.json
  LICENSE
  README.md
  package-lock.json
  src/components/CenterWrapper.tsx
  src/components/DynamicTitle.jsx
  src/features/Header/index.tsx
  src/pages/About.tsx
  src/pages/Startpage.tsx
  src/resources/images/FrontPage.png
  src/resources/images/Whoops.png
  src/resources/images/about1.png
  src/resources/images/portraits/charles.png
  src/resources/images/portraits/douglas.png
  src/resources/images/portraits/karl.png
  src/resources/images/portraits/kelvin.png
  src/resources/images/portraits/simon.png
  src/resources/images/underConstruction.png
Labels: rewrite

#96 Added feature to delete account
  src/features/settings/AccountSettings.tsx
  src/features/settings/DeleteAccountDialog.tsx
  src/features/settings/SecuritySettings.tsx
  src/features/users/usersSlice.ts
Labels: enhancement, rewrite

#98 Added use-dark-mode and implemented dark mode button
  package-lock.json
  package.json
  public/index.html
  src/components/ThemeLayer.tsx
  src/features/Header/index.tsx
  src/features/agora/index.tsx
Labels: design, enhancement, rewrite
