Repository digitalungdom-se/digitalungdom.se, pull requests merged in 2020-06, with the labels that each got.

#36 New and improved README
  README.md
Labels: documentation

#35 Added License
  LICENSE
Labels: documentation, enhancement

#41 Implemented a link for verifying email
  package-lock.json
  package.json
  src/components/ProfileHeaderButton.stories.tsx
  src/components/StoryMetadata.ts
  src/features/auth/VerifyEmailLink.stories.tsx
  src/features/auth/VerifyEmailLink.tsx
  src/features/auth/VerifyEmailPage.stories.tsx
  src/router/index.tsx
Labels: documentation, enhancement, front-end, rewrite
